name: llm
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - ipykernel
  - jupyterlab
  - numpy
  - matplotlib
  - xarray
  - pandas
  - cartopy
  - rioxarray
  - geopandas
  - pillow
  - scipy
  - seaborn
  - shapely
  - pyproj
